name: Release

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/main_ci.yml"
      - ".github/workflows/release.yml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "conanfile.py"
      - "vcpkg.json"
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-vcpkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          # - debug
          - release
        runtime:
          - all
          # - flatrim
          # - ae
          # - se
          # - vr
        compiler:
          - msvc
          # - clang-cl
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.22

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      # OTClient is made available under the MIT License
      # Copyright (c) 2010-2020 OTClient <https://github.com/edubart/otclient>
      # ref: https://github.com/mehah/otclient/actions/runs/13703854793/workflow#L42
      - name: Restore artifacts and install vcpkg
        id: vcpkg-step
        run: |
          $json=Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $vcpkgCommitId=$json.'builtin-baseline'
          Write-Host "vcpkg commit ID: $vcpkgCommitId"
          echo "vcpkgGitCommitId=$vcpkgCommitId" >> "$GITHUB_OUTPUT"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}
          doNotCache: true

      - name: Build
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
        continue-on-error: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
          path: ${{ github.workspace }}/build

      # - name: Release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     allowUpdates: true
      #     artifacts: |
