name: Release

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/main_ci.yml"
      - ".github/workflows/release.yml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "conanfile.py"
      - "vcpkg.json"
  pull_request:
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: fc3f61366102c1f0d4547c06d03c523bb18c13a7

jobs:
  build-and-test-vcpkg:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          # - debug
          - release
        runtime:
          - all
          # - flatrim
          # - ae
          # - se
          # - vr
        compiler:
          - msvc
          # - clang-cl
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.19

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: true

      # - name: Build
      #   uses: lukka/run-cmake@v10.8
      #   with:
      #     cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
      #     configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
      #     buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
      #   continue-on-error: true
      - name: Preset
        run: cmake --preset build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
        continue-on-error: true
      - name: Build
        run: cmake --build --preset ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
          path: ${{ github.workspace }}/build

      # - name: Release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     allowUpdates: true
      #     artifacts: |
